# Generated by Django 6.0.4 on 2026-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bloodrequest_status_donor_status_donor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
